# Base16 Atelier Plateau
# Author: Bram de Haan (http://atelierbramdehaan.nl)

[colors]
background=1b1818ff
text=8a8585ff
placeholder=655d5dff
prompt=8a8585ff
input=8a8585ff
match=a06e3bff
selection=655d5dff
selection-text=8a8585ff
selection-match=a06e3bff
counter=e7dfdfff
border=7272caff