# Base16 Circus
# Author: Stephan Boyer (https://github.com/stepchowfun) and Esther Wang (https://github.com/ewang12)

[colors]
background=191919ff
text=a7a7a7ff
placeholder=5f5a60ff
prompt=a7a7a7ff
input=a7a7a7ff
match=c3ba63ff
selection=5f5a60ff
selection-text=a7a7a7ff
selection-match=c3ba63ff
counter=808080ff
border=639ee4ff