# Base16 Atelier Cave
# Author: Bram de Haan (http://atelierbramdehaan.nl)

[colors]
background=19171cff
text=8b8792ff
placeholder=655f6dff
prompt=8b8792ff
input=8b8792ff
match=a06e3bff
selection=655f6dff
selection-text=8b8792ff
selection-match=a06e3bff
counter=e2dfe7ff
border=576ddbff